sudo: false
language: erlang
branches:
  only:
    - master
otp_release:
  - R16B03-1
  - 17.4
  - 18.3
  - 19.1
  - 19.1
  - 21.0
before_script:
  - psql -U postgres -c "create extension postgis"
addons:
  postgresql: "9.4"
script:
  - ./setup_test_db.sh
  - pg_ctl start -D datadir/ -o "-p 10432 -k `pwd`/datadir/"
  - sleep 1
  - make create_testdbs
  - make test
  - pg_ctl stop -D datadir/ || true 
