sudo: false
language: erlang
otp_release:
  - R16B03-1
  - 17.4
  - 18.3
  - 19.1
before_script:
  - psql -U postgres -c "create extension postgis"
addons:
  postgresql: "9.4"
script:
  - ./setup_test_db.sh
  - ./start_test_db.sh &
  - sleep 1
  - make create_testdbs
  - make test

